name: Rust Deploy

on:
    push:
        tags:
            - "*"


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true

            - name: Build
              run: cargo build --release

            - name: Publish
              run: |
                cargo publish --token ${{ secrets.CARGO_TOKEN }}

              env:
                    CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}

    create-release:
        runs-on: ubuntu-latest
        steps:
         - uses: actions/checkout@v4
         - uses: taiki-e/create-gh-release-action@v1
           with:
            # (required) GitHub token for creating GitHub Releases.
            token: ${{ secrets.ACTION_TOKEN }}

    upload-assets:
        needs: create-release
        strategy:
            matrix:
                include:
                    - name: Linux
                      os: ubuntu-latest
                      
                    - name: macOS
                      os: macos-latest
                      
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: taiki-e/upload-rust-binary-action@v1
              with:
               
                bin: filecrypt
               
                target: ${{ matrix.target }}

              
                tar: unix
               
                zip: windows
                # (required) GitHub token for uploading assets to GitHub Releases.
                token: ${{ secrets.ACTION_TOKEN }}

    